#!/usr/bin/env python3
"""
Generate Majorana-mode media for the OBC TFIM.

This script creates only MP4/GIF media. The final report PDFs are generated by
majorana_modes.py.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

if "MPLCONFIGDIR" not in os.environ:
    mpl_cache_dir = Path("/tmp/qising_1d_matplotlib_cache/majorana")
    mpl_cache_dir.mkdir(parents=True, exist_ok=True)
    os.environ["MPLCONFIGDIR"] = str(mpl_cache_dir)

import matplotlib.animation as animation
import matplotlib.pyplot as plt
import numpy as np

from majorana_modes import (
    AXIS_LABEL_FONTSIZE,
    PROJECT_ROOT,
    TEXT_FONTSIZE,
    TICK_FONTSIZE,
    majorana_profile_density,
)


PLOT_DIR = PROJECT_ROOT / "plots" / "h_null" / "majorana"
DEFAULT_L = 22

# MP4 settings: smooth enough for presentations, still small enough to store.
FPS_VIDEO = 60
DURATION_SEC_VIDEO = 15
TOTAL_FRAMES_VIDEO = FPS_VIDEO * DURATION_SEC_VIDEO
FRAMES_TOPO_VIDEO = int(TOTAL_FRAMES_VIDEO * 0.75)
FRAMES_TRIVIAL_VIDEO = TOTAL_FRAMES_VIDEO - FRAMES_TOPO_VIDEO

# GIF settings: shorter and lower frame-rate for GitHub/README usage.
FPS_GIF = 15
DURATION_SEC_GIF = 8
TOTAL_FRAMES_GIF = FPS_GIF * DURATION_SEC_GIF
FRAMES_TOPO_GIF = int(TOTAL_FRAMES_GIF * 0.70)
FRAMES_TRIVIAL_GIF = TOTAL_FRAMES_GIF - FRAMES_TOPO_GIF


def timeline(topological_frames: int, trivial_frames: int) -> np.ndarray:
    """Sweep from the ordered edge-mode regime through the transition."""
    return np.concatenate([
        np.linspace(0.10, 0.99, topological_frames),
        np.linspace(0.99, 1.30, trivial_frames),
    ])


def xi_label(g: float) -> str:
    """Small on-screen label for the edge-mode decay length."""
    if 0.0 < g < 1.0:
        return rf"$\xi_M \simeq {-1.0 / np.log(g):.2f}$ sites"
    return r"bulk mode, no edge localization"


def animate_cinematic_majorana(L: int = DEFAULT_L) -> Path:
    """Render the MP4 visualization of edge-mode hybridisation."""
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    g_frames = timeline(FRAMES_TOPO_VIDEO, FRAMES_TRIVIAL_VIDEO)
    sites = np.arange(1, L + 1)

    # Dark styling is used only for the media files, not for report PDFs.
    plt.style.use("dark_background")
    fig, ax = plt.subplots(figsize=(12, 7), facecolor="#0B0C10")
    ax.set_facecolor("#0B0C10")
    ax.set_xlim(0.5, L + 0.5)
    ax.set_ylim(0.0, 0.55)
    ax.set_xlabel(r"site $j$", fontsize=AXIS_LABEL_FONTSIZE, color="#66FCF1", labelpad=10)
    ax.set_ylabel(r"Majorana profile $|\Phi_j|^2$", fontsize=AXIS_LABEL_FONTSIZE, color="#66FCF1", labelpad=10)
    ax.tick_params(colors="#C5C6C7", labelsize=TICK_FONTSIZE, direction="in")
    ax.grid(color="#1F2833", linestyle=":", linewidth=0.7, alpha=0.8)
    for spine in ax.spines.values():
        spine.set_color("#1F2833")

    # Multiple coincident lines create a lightweight glow effect in the video.
    glow_lines = []
    for lw, alpha in [(9, 0.05), (6, 0.15), (3, 0.4), (1.5, 1.0)]:
        line, = ax.plot([], [], "-", lw=lw, alpha=alpha, solid_capstyle="round")
        glow_lines.append(line)
    scatter_pts, = ax.plot([], [], "o", ms=5.5, color="#FFFFFF", zorder=5)
    text_g = ax.text(0.5, 0.92, "", transform=ax.transAxes, ha="center", fontsize=AXIS_LABEL_FONTSIZE, color="#FFFFFF")
    text_xi = ax.text(0.5, 0.84, "", transform=ax.transAxes, ha="center", fontsize=TEXT_FONTSIZE, color="#C5C6C7")

    def update(frame_idx: int):
        """Update one animation frame from the current transverse field."""
        g = float(g_frames[frame_idx])
        rho = majorana_profile_density(L, g)
        neon_color = "#66FCF1" if g < 1.0 else "#FF0055"
        fill_color = "#45A29E" if g < 1.0 else "#C3073F"
        for line in glow_lines:
            line.set_data(sites, rho)
            line.set_color(neon_color)
        scatter_pts.set_data(sites, rho)
        scatter_pts.set_color(neon_color)
        # fill_between creates a PolyCollection each frame; remove the
        # previous shaded density before drawing the next one.
        while ax.collections:
            ax.collections[0].remove()
        ax.fill_between(sites, 0.0, rho, color=fill_color, alpha=0.20)
        text_g.set_text(rf"OBC, $L={L}$, $g={g:.3f}$")
        text_xi.set_text(xi_label(g))
        return glow_lines + [scatter_pts, text_g, text_xi]

    ani = animation.FuncAnimation(fig, update, frames=TOTAL_FRAMES_VIDEO, blit=False, interval=1000 / FPS_VIDEO)
    out_path = PLOT_DIR / "majorana_cinematic_60fps.mp4"
    writer = animation.FFMpegWriter(fps=FPS_VIDEO, bitrate=5000)
    ani.save(out_path, writer=writer)
    plt.close(fig)
    print(f"[OK] {out_path.relative_to(PROJECT_ROOT)}")
    return out_path


def animate_github_readme_gif(L: int = DEFAULT_L) -> Path:
    """Render a compact GIF version for README or slides."""
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    g_frames = timeline(FRAMES_TOPO_GIF, FRAMES_TRIVIAL_GIF)
    sites = np.arange(1, L + 1)

    plt.style.use("dark_background")
    fig, ax = plt.subplots(figsize=(8, 4.5), dpi=80, facecolor="#0B0C10")
    ax.set_facecolor("#0B0C10")
    ax.set_xlim(0.5, L + 0.5)
    ax.set_ylim(0.0, 0.55)
    ax.set_ylabel(r"$|\Phi_j|^2$", fontsize=AXIS_LABEL_FONTSIZE, color="#66FCF1", labelpad=5)
    ax.tick_params(colors="#C5C6C7", labelsize=TICK_FONTSIZE, direction="in")
    ax.grid(color="#1F2833", linestyle=":", linewidth=0.5, alpha=0.6)
    for spine in ax.spines.values():
        spine.set_visible(False)

    # A reduced glow stack keeps the GIF palette compact.
    glow_lines = []
    for lw, alpha in [(7, 0.1), (1.5, 1.0)]:
        line, = ax.plot([], [], "-", lw=lw, alpha=alpha, solid_capstyle="round")
        glow_lines.append(line)
    text_g = ax.text(0.5, 0.93, "", transform=ax.transAxes, ha="center", fontsize=AXIS_LABEL_FONTSIZE, color="#FFFFFF")
    text_xi = ax.text(0.5, 0.86, "", transform=ax.transAxes, ha="center", fontsize=TEXT_FONTSIZE, color="#C5C6C7")

    def update(frame_idx: int):
        """Update one low-bandwidth GIF frame."""
        g = float(g_frames[frame_idx])
        rho = majorana_profile_density(L, g)
        neon_color = "#66FCF1" if g < 1.0 else "#FF0055"
        fill_color = "#45A29E" if g < 1.0 else "#C3073F"
        for line in glow_lines:
            line.set_data(sites, rho)
            line.set_color(neon_color)
        while ax.collections:
            ax.collections[0].remove()
        ax.fill_between(sites, 0.0, rho, color=fill_color, alpha=0.10)
        text_g.set_text(rf"OBC, $g={g:.2f}$")
        text_xi.set_text(xi_label(g))
        return glow_lines + [text_g, text_xi]

    ani = animation.FuncAnimation(fig, update, frames=TOTAL_FRAMES_GIF, blit=True, interval=1000 / FPS_GIF)
    out_path = PLOT_DIR / "majorana_github_readme.gif"
    writer = animation.PillowWriter(fps=FPS_GIF)
    ani.save(out_path, writer=writer)
    plt.close(fig)
    file_size_mb = out_path.stat().st_size / (1024 * 1024)
    print(f"[OK] {out_path.relative_to(PROJECT_ROOT)} ({file_size_mb:.2f} MB)")
    return out_path


def parse_args() -> argparse.Namespace:
    """Command-line interface for optional media regeneration."""
    parser = argparse.ArgumentParser(description="Generate Majorana MP4/GIF media only.")
    parser.add_argument("--L", type=int, default=DEFAULT_L, help="BdG chain length for media frames.")
    parser.add_argument("--skip-mp4", action="store_true")
    parser.add_argument("--skip-gif", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.skip_mp4:
        print("[majorana_media.py] Rendering MP4 ...")
        animate_cinematic_majorana(L=args.L)
    if not args.skip_gif:
        print("[majorana_media.py] Rendering GIF ...")
        animate_github_readme_gif(L=args.L)
    if args.skip_mp4 and args.skip_gif:
        print("[majorana_media.py] Nothing to render.")


if __name__ == "__main__":
    main()
